image: privacybydesign/node_yarn:latest

stages:
  - build
  
before_script:
  - set -euxo pipefail
  - apt-get update
  - apt-get install -y --no-install-recommends php composer
  - composer install
  - yarn install

build:
  stage: build
  script:
    - ./build_artifacts.sh
  artifacts:
    paths:
      - build/*