image: privacybydesign/node_yarn:latest

stages:
  - build
  
before_script:
  - set -euxo pipefail
  - php composer.phar install
  - yarn install

build:
  stage: build
  script:
    - ./build_artifacts.sh
  artifacts:
    paths:
      - build/*